"""EUDR role constants — single source of truth for RBAC."""

SUPER_ADMIN = "SUPER_ADMIN"
TENANT_ADMIN = "TENANT_ADMIN"
TECNICO_CAMPO = "TECNICO_CAMPO"
AUDITOR_INTERNO = "AUDITOR_INTERNO"
PRODUCTOR = "PRODUCTOR"

EUDR_ROLES: tuple[str, ...] = (
    SUPER_ADMIN,
    TENANT_ADMIN,
    TECNICO_CAMPO,
    AUDITOR_INTERNO,
    PRODUCTOR,
)

DEFAULT_ROLE = PRODUCTOR
