import { StyleSheet, Platform } from 'react-native';
import { theme } from '../../../theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.primary },
  header: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 5 },
  mainTitle: { ...theme.typography.headlineLgMobile, color: '#fff', fontSize: 24, marginBottom: 10 },
  progressContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 10 },
  stepIndicatorWrapper: { flexDirection: 'row', alignItems: 'center' },
  stepCircle: { width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'rgba(255,255,255,0.3)' },
  stepCircleActive: { backgroundColor: theme.colors.secondary, borderColor: '#fff' },
  stepNumber: { color: 'rgba(255,255,255,0.6)', fontWeight: 'bold' },
  stepNumberActive: { color: '#fff' },
  stepLine: { width: 40, height: 3, backgroundColor: 'rgba(255,255,255,0.2)' },
  stepLineActive: { backgroundColor: theme.colors.secondary },
  formScroll: { flex: 1, backgroundColor: 'rgba(0,0,0,0.05)' },
  formContent: { paddingHorizontal: 20, paddingBottom: 100 },
  stepContent: { paddingTop: 20 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.1)', paddingBottom: 8 },
  sectionTitle: { ...theme.typography.labelMd, fontSize: 18, color: '#fff', marginLeft: 10, fontWeight: 'bold' },
  denseForm: { paddingHorizontal: 2 },
  inputGroupDense: { marginBottom: 12 },
  labelSmall: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginBottom: 4, fontWeight: '600' },
  inputDense: { backgroundColor: '#fff', borderRadius: 8, height: 42, paddingHorizontal: 12, color: '#000', fontSize: 15 },
  inputDisabled: { backgroundColor: '#eee', color: '#666' },
  disabledInputRow: { flexDirection: 'row', alignItems: 'center' },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryFixed,
    padding: 12,
    borderRadius: 12,
    marginTop: 15,
  },
  infoText: {
    ...theme.typography.labelSm,
    color: theme.colors.onPrimaryFixed,
    marginLeft: 8,
    flex: 1,
  },
  inputGroup: { marginBottom: 15 },
  label: { ...theme.typography.labelSm, color: '#fff', marginBottom: 6, fontWeight: '600' },
  input: { backgroundColor: '#fff', borderRadius: 10, height: 50, paddingHorizontal: 15, color: '#000', fontSize: 16 },
  disabledInput: { backgroundColor: '#e0e0e0', justifyContent: 'center' },
  totalStockBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.secondaryFixed,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.secondary,
  },
  totalStockValue: {
    ...theme.typography.headlineMd,
    color: theme.colors.onSecondaryFixedVariant,
    marginLeft: 10,
    fontWeight: '700',
  },
  eudrIdCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  eudrIdIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  eudrIdContent: {
    flex: 1,
  },
  eudrIdCode: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1.2,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  eudrIdLabel: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 10,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  row: { flexDirection: 'row', marginBottom: 10 },
  locationButton: { backgroundColor: theme.colors.secondary, borderRadius: 10, height: 45, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 15 },
  locationButtonText: { color: '#fff', fontWeight: 'bold', marginLeft: 5 },
  miniMapCard: { backgroundColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 15, padding: 10, marginVertical: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  miniMapHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  miniMapTitle: { color: '#fff', fontSize: 14, fontWeight: 'bold', marginLeft: 8 },
  miniMapWrapper: { height: 150, borderRadius: 10, overflow: 'hidden' },
  footer: { flexDirection: 'row', padding: 12, backgroundColor: theme.colors.primary, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'space-between' },
  navButtonPrimary: { flex: 1, backgroundColor: theme.colors.secondary, height: 46, borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  navButtonSecondary: { flex: 1, backgroundColor: 'rgba(255,255,255,0.1)', height: 46, borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  navButtonText: { color: '#fff', fontSize: 15, fontWeight: 'bold', marginHorizontal: 6 },
  submitButton: { flex: 1, backgroundColor: '#4CAF50', height: 46, borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  submitButtonText: { color: '#fff', fontSize: 15, fontWeight: 'bold', textTransform: 'uppercase' },
  dynamicFieldRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  addFieldButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#fff', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, marginTop: 5 },
  addFieldText: { color: theme.colors.primary, fontWeight: 'bold', marginLeft: 5 },
});
