export const theme = {
  name: 'Altitude Trace',
  colors: {
    surface: '#f5f7fa',
    onSurface: '#141b2b',
    onSurfaceVariant: '#404942',
    inverseSurface: '#293040',
    inverseOnSurface: '#edf0ff',
    outline: '#707971',
    outlineVariant: '#bfc9c0',
    surfaceTint: '#226b47',
    primary: '#004328',
    onPrimary: '#ffffff',
    primaryContainer: '#0d5c3a',
    onPrimaryContainer: '#8ad2a7',
    inversePrimary: '#8ed6aa',
    secondary: '#775a19',
    onSecondary: '#ffffff',
    secondaryContainer: '#fed488',
    onSecondaryContainer: '#785a1a',
    tertiary: '#632527',
    onTertiary: '#ffffff',
    tertiaryContainer: '#803b3c',
    onTertiaryContainer: '#ffaeac',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#a9f3c5',
    primaryFixedDim: '#8ed6aa',
    onPrimaryFixed: '#002111',
    onPrimaryFixedVariant: '#005232',
    secondaryFixed: '#ffdea5',
    secondaryFixedDim: '#e9c176',
    onSecondaryFixed: '#261900',
    onSecondaryFixedVariant: '#5d4201',
    tertiaryFixed: '#ffdad8',
    tertiaryFixedDim: '#ffb3b2',
    onTertiaryFixed: '#3c070b',
    onTertiaryFixedVariant: '#743233',
    background: '#f9f9ff',
    onBackground: '#141b2b',
    surfaceVariant: '#dce2f7',
  },
  typography: {
    // Nota: Geist debe ser cargada en el proyecto. Por ahora usaremos sans-serif como fallback.
    display: {
      fontSize: 48,
      fontWeight: '600',
      lineHeight: 52,
      letterSpacing: -0.96,
    },
    headlineLg: {
      fontSize: 32,
      fontWeight: '600',
      lineHeight: 38,
      letterSpacing: -0.32,
    },
    headlineLgMobile: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 28,
      letterSpacing: -0.24,
    },
    headlineMd: {
      fontSize: 24,
      fontWeight: '500',
      lineHeight: 31,
    },
    bodyLg: {
      fontSize: 18,
      fontWeight: '400',
      lineHeight: 28,
    },
    bodyMd: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    labelMd: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 16,
      letterSpacing: 0.28,
    },
    labelSm: {
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 14,
    },
  },
  roundness: {
    sm: 2,
    default: 4,
    md: 6,
    lg: 8,
    xl: 12,
    full: 9999,
  },
  spacing: {
    base: 4,
    xs: 8,
    sm: 16,
    md: 24,
    lg: 40,
    xl: 64,
    gutter: 24,
    marginMobile: 16,
    marginDesktop: 48,
  },
};
